modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="guardapanda"
version="1.0.0"
displayName="Login"
displayURL="https://github.com/joaoespanhol/Login"
authors="guardapanda"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.guardapanda]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration